#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# Git identity
# ------------------------------------------------------------------------------

git_identity_state_file() {
    local home_dir="$1"

    printf '%s\n' "$home_dir/.local/state/dotfiles/git/identity.gitconfig"
}

write_git_identity_state() {
    local home_dir="$1"
    local name="$2"
    local email="$3"
    local state_file
    local state_dir
    local temporary_file
    local backup
    local timestamp

    state_file="$(git_identity_state_file "$home_dir")"
    state_dir="$(dirname "$state_file")"

    mkdir -p "$state_dir" || {
        log_error "Unable to create Git identity state directory: $state_dir"
        return 1
    }

    temporary_file="$(mktemp "$state_file.tmp.XXXXXX")" || {
        log_error "Unable to create temporary Git identity state file."
        return 1
    }

    {
        printf '# Generated by the dotfiles installer.\n'
        printf '[user]\n'
        printf '\tname = %s\n' "$name"
        printf '\temail = %s\n' "$email"
    } > "$temporary_file"

    if [[ -f "$state_file" ]] && cmp -s "$temporary_file" "$state_file"; then
        rm "$temporary_file"
        log_skip "Git identity state unchanged."
        return 0
    fi

    if [[ -e "$state_file" || -L "$state_file" ]]; then
        timestamp="$(date '+%Y%m%d-%H%M%S')"
        backup="$state_file.backup-$timestamp"
        while [[ -e "$backup" || -L "$backup" ]]; do
            timestamp="$(date '+%Y%m%d-%H%M%S')"
            backup="$state_file.backup-$timestamp"
            sleep 1
        done
        mv "$state_file" "$backup" || {
            rm "$temporary_file"
            log_error "Unable to back up Git identity state."
            return 1
        }
        log_info "Created Git identity state backup."
    fi

    mv "$temporary_file" "$state_file" || {
        log_error "Unable to save Git identity state."
        return 1
    }

    log_success "Saved Git identity state."
}

configure_git_identity() {
    local home_dir="$1"
    local name="${DOTFILES_GIT_NAME:-}"
    local email="${DOTFILES_GIT_EMAIL:-}"
    local existing_name
    local existing_email
    local entered

    existing_name="$(git config --global --get user.name 2>/dev/null || true)"
    existing_email="$(git config --global --get user.email 2>/dev/null || true)"

    [[ -n "$name" ]] || name="$existing_name"
    [[ -n "$email" ]] || email="$existing_email"

    if [[ -z "$name" || -z "$email" ]]; then
        if [[ "${NON_INTERACTIVE:-false}" == true || ! -t 0 || ! -t 1 ]]; then
            log_info "Git identity not configured; provide --git-name and --git-email to configure it."
            return 0
        fi

        printf 'Git user.name [%s]: ' "$name"
        IFS= read -r entered
        [[ -n "$entered" ]] && name="$entered"

        printf 'Git user.email [%s]: ' "$email"
        IFS= read -r entered
        [[ -n "$entered" ]] && email="$entered"
    fi

    if [[ -z "$name" || -z "$email" ]]; then
        log_info "Git identity not configured."
        return 0
    fi

    write_git_identity_state "$home_dir" "$name" "$email"
}

# ------------------------------------------------------------------------------
# Git remote access
# ------------------------------------------------------------------------------

verify_git_remote() {
    if git ls-remote --exit-code origin HEAD >/dev/null 2>&1; then
        log_success "Git remote read access verified."
        return 0
    fi

    if [[ "${REQUIRE_REMOTE:-false}" == true ]]; then
        log_error "Unable to access the Git remote."
        return 1
    fi

    log_info "Git remote access unavailable; continuing with local installation."
}
