#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# Zsh integration selection
# ------------------------------------------------------------------------------

select_zsh_integrations() {
    local choices=("Starship prompt")
    local selected=(1)
    local cursor=0
    local key
    local index

    DOTFILES_ZSH_INTEGRATIONS_ALL=0
    ZSH_INTEGRATION_STARSHIP=0

    if [[ "${NON_INTERACTIVE:-false}" == true || ! -t 0 || ! -t 1 ]]; then
        DOTFILES_ZSH_INTEGRATIONS_ALL=1
        ZSH_INTEGRATION_STARSHIP=1
        return 0
    fi

    while true; do
        printf '\033[2J\033[H'
        printf 'ZSH Integrations\n\n'

        for index in "${!choices[@]}"; do
            if [[ "$index" == "$cursor" ]]; then
                printf '  > '
            else
                printf '    '
            fi

            if [[ "${selected[$index]}" == 1 ]]; then
                printf '[x] %s\n' "${choices[$index]}"
            else
                printf '[ ] %s\n' "${choices[$index]}"
            fi
        done

        printf '\nUse UP/DOWN to move, SPACE to toggle, ENTER to continue, Q to cancel\n'

        IFS= read -rsn1 key || return 1
        case "$key" in
            $'\x1b')
                IFS= read -rsn2 key || return 1
                case "$key" in
                    '[A')
                        if ((cursor > 0)); then
                            cursor=$((cursor - 1))
                        fi
                        ;;
                    '[B')
                        if ((cursor < ${#choices[@]} - 1)); then
                            cursor=$((cursor + 1))
                        fi
                        ;;
                esac
                ;;
            ' ')
                if [[ "${selected[$cursor]}" == 1 ]]; then
                    selected[$cursor]=0
                else
                    selected[$cursor]=1
                fi
                ;;
            '')
                break
                ;;
            [qQ])
                printf '\nSelection cancelled.\n' >&2
                return 1
                ;;
        esac
    done

    printf '\033[2J\033[H'
    ZSH_INTEGRATION_STARSHIP="${selected[0]}"
}

write_zsh_integration_state() {
    local home_dir="$1"
    local state_home="${XDG_STATE_HOME:-$home_dir/.local/state}"
    local state_dir="$state_home/dotfiles/selections/zsh-integrations"
    local state_file="$state_dir/enabled.zsh"
    local temporary_file
    local backup
    local timestamp

    mkdir -p "$state_dir" || {
        log_error "Unable to create integration state directory: $state_dir"
        return 1
    }

    temporary_file="$(mktemp "$state_file.tmp.XXXXXX")" || {
        log_error "Unable to create temporary integration state file."
        return 1
    }

    {
        printf '# Generated by the dotfiles installer.\n'
        printf 'DOTFILES_ZSH_INTEGRATIONS_ALL=%s\n' "${DOTFILES_ZSH_INTEGRATIONS_ALL:-0}"
        printf 'ZSH_INTEGRATION_STARSHIP=%s\n' "${ZSH_INTEGRATION_STARSHIP:-0}"
    } > "$temporary_file"

    if [[ -f "$state_file" ]] && cmp -s "$temporary_file" "$state_file"; then
        rm "$temporary_file"
        log_skip "ZSH integration state unchanged: $state_file"
        return 0
    fi

    if [[ -e "$state_file" || -L "$state_file" ]]; then
        timestamp="$(date '+%Y%m%d-%H%M%S')"
        backup="$state_file.backup-$timestamp"
        while [[ -e "$backup" || -L "$backup" ]]; do
            timestamp="$(date '+%Y%m%d-%H%M%S')"
            backup="$state_file.backup-$timestamp"
            sleep 1
        done
        mv "$state_file" "$backup" || {
            rm "$temporary_file"
            log_error "Unable to back up integration state: $state_file"
            return 1
        }
        log_info "Created integration state backup: $backup"
    fi

    mv "$temporary_file" "$state_file" || {
        log_error "Unable to save integration state: $state_file"
        return 1
    }

    log_success "Saved ZSH integration state: $state_file"
}
